### ISSUE TITLE
CacheCoreH2 failed

### ISSUE THREAD

**Issue by nara007** [AKSW/jena-sparql-api#9]
I want to add Caching to my Endpoint Proxy. But the cache code does not work. 
The endpoint that i use is  DBpedia.

![image-2](https://cloud.githubusercontent.com/assets/9050331/8556745/530aeeb8-24f9-11e5-8b04-be40c9424658.png)
![image](https://cloud.githubusercontent.com/assets/9050331/8556746/530c3f02-24f9-11e5-854a-7601e6dd1ffb.png)

**Comment by jimkont** [comment]
See here for an example
https://github.com/AKSW/RDFUnit/blob/master/rdfunit-core/src/main/java/org/aksw/rdfunit/sources/TestSource.java#L108-116
